name: release
on:
  workflow_dispatch:
    inputs:
      src_folder:
        description: 'Folder to copy from'    # Descrizione del parametro di origine
        required: true
        default: 'source_folder'             # Valore predefinito
      dest_folder:
        description: 'Folder to copy to'      # Descrizione del parametro di destinazione
        required: true
        default: 'destination_folder'        # Valore predefinito

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set paths
        id: set_paths
        run: |
          base_path="flux-configs"       # Percorso di base per la cartella di origine
          
          # Percorsi completi unendo i percorsi base con i parametri dell'utente
          src_folder_input="${{ github.event.inputs.src_folder }}"
          src_folder="$base_path/$src_folder_input"
          echo "src_folder: $src_folder"
          dest_folder_input="${{ github.event.inputs.dest_folder }}"
          dest_folder="$base_path/$dest_folder_input"
          echo "dest_folder: $dest_folder"

          # Nome dinamico del file zip che include i percorsi e il timestamp
          timestamp=$(date +%Y%m%d%H%M%S)
          zip_file="${src_folder_input//\//_}_${dest_folder_input//\//_}_$timestamp.zip"
          echo "ZIP file name: $zip_file"
          
          # Usa GITHUB_OUTPUT per impostare le variabili di output
          echo "src_folder=$src_folder" >> $GITHUB_OUTPUT
          echo "dest_folder=$dest_folder" >> $GITHUB_OUTPUT
          echo "zip_file=$zip_file" >> $GITHUB_OUTPUT

      - name: Zip and move destination folder content
        run: |
          mkdir -p "${{ steps.set_paths.outputs.dest_folder }}"   # Assicurati che la cartella di destinazione esista

          # Comprimi il contenuto della cartella di destinazione solo se contiene file
          if [ "$(ls -A ${{ steps.set_paths.outputs.dest_folder }})" ]; then
            zip -r "${{ steps.set_paths.outputs.zip_file }}" "${{ steps.set_paths.outputs.dest_folder }}"
          else
            echo "Destination folder is empty, skipping ZIP creation."
          fi

          # Se il file ZIP è stato creato, spostalo nella cartella base del repository
          mkdir -p "backup"   # Assicurati che la cartella di destinazione esista
          if [ -f "${{ steps.set_paths.outputs.zip_file }}" ]; then
            mv "${{ steps.set_paths.outputs.zip_file }}" ./backup
          fi

      - name: Clear destination folder
        run: |
          # Cancella il contenuto della cartella di destinazione
          rm -rf "${{ steps.set_paths.outputs.dest_folder }}/*"

      - name: Copy files
        run: |
          mkdir -p "${{ steps.set_paths.outputs.dest_folder }}"                # Crea la cartella di destinazione se non esiste
          cp -r "${{ steps.set_paths.outputs.src_folder }}/." "${{ steps.set_paths.outputs.dest_folder }}/"  # Copia i file dalla sorgente alla destinazione

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ steps.set_paths.outputs.dest_folder }}/*" "${{ steps.set_paths.outputs.zip_file }}"
          git commit -m "Copy files from ${{ steps.set_paths.outputs.src_folder }} to ${{ steps.set_paths.outputs.dest_folder }}, create backup, and clear old content"
          git push